base:
  project: Deep Learning Project for Youtube Channel

data_source:
  data_src: data_source

load_data:
  num_classes: 4
  raw_data: data_source
  preprocessed_data: data/processed
  full_Path: deep_learning/Data_Set

train_split:
  split_ratio: 80

model:
  name: MRI_BRAIN_TUMOR
  trainable: True
  train_path: data/processed/train
  test_path: data/processed/test
  image_size: [244,244]
  loss: 'categorical_crossentropy'
  optimizer: 'adam'
  metrics: ['accuracy']
  epochs: 7
  sav_dir: saved_models/trained.h5

img_augment:
  rescale: 1./255,
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True
  vertical_flip: True
  batch_size: 18
  class_mode: 'categorical'


model_dir: saved_models

web_model_directory: saved_models/trained.h5

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Deep_Learning_CNN
  run_name: mlops
  registered_model_name: Deep_Learning
  remote_server_uri: http://127.0.0.1:5000


