channels:
- conda-forge
dependencies:
- python=3.7.6
- pip<=22.3.1
- pip:
  - mlflow
  - boto3==1.26.5
  - cffi==1.15.1
  - fsspec==2022.10.0
  - keras==2.10.0
  - pandas==1.3.5
  - pillow==9.3.0
  - pydot==1.4.2
  - scipy==1.7.3
  - tensorflow==2.10.0
name: mlflow-env
